<?php

use Illuminate\Database\Seeder;

class SettingsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('settings')->insert([
            [
                'scope' => 'Web',
                'input_type' => 'file',
                'settings_label' => 'Logo',
                'settings_name' => 'logo',
                'value' => '',
                'priority' => '1',
                'is_active' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'scope' => 'Web',
                'input_type' => 'file',
                'settings_label' => 'Favicon Icon',
                'settings_name' => 'favicon_icon',
                'value' => '',
                'priority' => '2',
                'is_active' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'scope' => 'Web',
                'input_type' => 'textbox',
                'settings_label' => 'Title Bar',
                'settings_name' => 'title_bar',
                'value' => '',
                'priority' => '3',
                'is_active' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'scope' => 'Web',
                'input_type' => 'textbox',
                'settings_label' => 'Facebook Link',
                'settings_name' => 'facebook_link',
                'value' => '',
                'priority' => '4',
                'is_active' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'scope' => 'Web',
                'input_type' => 'textbox',
                'settings_label' => 'Google Plus Link',
                'settings_name' => 'google_plus_link',
                'value' => '',
                'priority' => '5',
                'is_active' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'scope' => 'Web',
                'input_type' => 'textbox',
                'settings_label' => 'Twitter Link',
                'settings_name' => 'twitter_link',
                'value' => '',
                'priority' => '6',
                'is_active' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'scope' => 'Web',
                'input_type' => 'textbox',
                'settings_label' => 'LinkedIn Link',
                'settings_name' => 'linkedin_link',
                'value' => '',
                'priority' => '7',
                'is_active' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'scope' => 'Page',
                'input_type' => 'textarea',
                'settings_label' => 'About Us',
                'settings_name' => 'about_us',
                'value' => '',
                'priority' => '1',
                'is_active' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'scope' => 'Page',
                'input_type' => 'textarea',
                'settings_label' => 'Contact Us',
                'settings_name' => 'contact_us',
                'value' => '',
                'priority' => '2',
                'is_active' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'scope' => 'Page',
                'input_type' => 'textarea',
                'settings_label' => 'Terms And Conditions',
                'settings_name' => 'terms_and_conditions',
                'value' => '',
                'priority' => '3',
                'is_active' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'scope' => 'Page',
                'input_type' => 'textarea',
                'settings_label' => 'Privacy Policies',
                'settings_name' => 'privacy_policies',
                'value' => '',
                'priority' => '4',
                'is_active' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'scope' => 'Page',
                'input_type' => 'textarea',
                'settings_label' => 'Refund Policies',
                'settings_name' => 'refund_policies',
                'value' => '',
                'priority' => '5',
                'is_active' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'scope' => 'Page',
                'input_type' => 'textarea',
                'settings_label' => 'FAQs',
                'settings_name' => 'faq',
                'value' => '',
                'priority' => '6',
                'is_active' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'scope' => 'App',
                'input_type' => 'textbox',
                'settings_label' => 'Radius',
                'settings_name' => 'radius',
                'value' => '',
                'priority' => '1',
                'is_active' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'scope' => 'App',
                'input_type' => 'textbox',
                'settings_label' => 'Google API Key',
                'settings_name' => 'google_api_key',
                'value' => '',
                'priority' => '2',
                'is_active' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'scope' => 'App',
                'input_type' => 'textbox',
                'settings_label' => 'Play Store Link',
                'settings_name' => 'play_store_link',
                'value' => '',
                'priority' => '3',
                'is_active' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'scope' => 'App',
                'input_type' => 'textbox',
                'settings_label' => 'App Store Link',
                'settings_name' => 'app_store_link',
                'value' => '',
                'priority' => '4',
                'is_active' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'scope' => 'App',
                'input_type' => 'textbox',
                'settings_label' => 'Google Direction API Key',
                'settings_name' => 'google_direction_api_key',
                'value' => '',
                'priority' => '5',
                'is_active' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'scope' => 'App',
                'input_type' => 'textbox',
                'settings_label' => 'Facebook Secret Key App ID',
                'settings_name' => 'facebook_secret_key_app_appId',
                'value' => '',
                'priority' => '6',
                'is_active' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'scope' => 'App',
                'input_type' => 'textbox',
                'settings_label' => 'Google Plus Secret Key App ID',
                'settings_name' => 'google_plus_secret_key_app_appId',
                'value' => '',
                'priority' => '7',
                'is_active' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
